Inventaire:

  commande:
  lignes:
  nom:
  nombreitem:

  block1:
    case:
    surnom:
    type:
    cmd:
  block2:
    case:
    surnom:
    type:
    cmd:
  block2:
    case:
    surnom:
    type:
    cmd:
  block3:
    case:
    surnom:
    type:
    cmd:
  block4:
    case:
    surnom:
    type:
    cmd:
  block5:
    case:
    surnom:
    type:
    cmd:
  block6:
    case:
    surnom:
    type:
    cmd:
  block7:
    case:
    surnom:
    type:
    cmd:
  block8:
    case:
    surnom:
    type:
    cmd:
  block9:
    case:
    surnom:
    type:
    cmd:
  block10:
    case:
    surnom:
    type:
    cmd:
  block11:
    case:
    surnom:
    type:
    cmd:
  block12:
    case:
    surnom:
    type:
    cmd:
  block13:
    case:
    surnom:
    type:
    cmd:
  block14:
    case:
    surnom:
    type:
    cmd:
  block15:
    case:
    surnom:
    type:
    cmd:
  block16:
    case:
    surnom:
    type:
    cmd:
  block17:
    case:
    surnom:
    type:
    cmd:
  block18:
    case:
    surnom:
    type:
    cmd:
  block19:
    case:
    surnom:
    type:
    cmd:
  block20:
    case:
    surnom:
    type:
    cmd:
  block21:
    case:
    surnom:
    type:
    cmd:
  block22:
    case:
    surnom:
    type:
    cmd:
  block23:
    case:
    surnom:
    type:
    cmd:
  block24:
    case:
    surnom:
    type:
    cmd:
  block25:
    case:
    surnom:
    type:
    cmd:
  block26:
    case:
    surnom:
    type:
    cmd:
  block27:
    case:
    surnom:
    type:
    cmd:
  block28:
    case:
    surnom:
    type:
    cmd:
  block29:
    case:
    surnom:
    type:
    cmd:
  block30:
    case:
    surnom:
    type:
    cmd:
  block31:
    case:
    surnom:
    type:
    cmd:
  block32:
    case:
    surnom:
    type:
    cmd:
  block33:
    case:
    surnom:
    type:
    cmd:
  block34:
    case:
    surnom:
    type:
    cmd:
  block35:
    case:
    surnom:
    type:
    cmd:
  block36:
    case:
    surnom:
    type:
    cmd:
  block37:
    case:
    surnom:
    type:
    cmd:
  block38:
    case:
    surnom:
    type:
    cmd:
  block39:
    case:
    surnom:
    type:
    cmd:
  block40:
    case:
    surnom:
    type:
    cmd:
  block41:
    case:
    surnom:
    type:
    cmd:
  block42:
    case:
    surnom:
    type:
    cmd:
  block43:
    case:
    surnom:
    type:
    cmd:
  block44:
    case:
    surnom:
    type:
    cmd:
  block45:
    case:
    surnom:
    type:
    cmd:
  block46:
    case:
    surnom:
    type:
    cmd:
  block47:
    case:
    surnom:
    type:
    cmd:
  block48:
    case:
    surnom:
    type:
    cmd:
  block49:
    case:
    surnom:
    type:
    cmd:
  block50:
    case:
    surnom:
    type:
    cmd:
  block51:
    case:
    surnom:
    type:
    cmd:
  block52:
    case:
    surnom:
    type:
    cmd:
  block53:
    case:
    surnom:
    type:
    cmd:
  block54:
    case:
    surnom:
    type:
    cmd:
